#!/bin/bash


#creating  variables and storing the code to get the info.
# System Information
HOSTNAME=$(hostname)
OS=$(awk -F= 'NR<=3 && /^NAME|^VERSION/{gsub(/\"/, "", $2); printf "%s ", $2}' /etc/os-release)
UPTIME=$(uptime -p)

# Hardware Information
CPU=$(sudo lshw -class processor | awk '/product/{gsub("product:",""); gsub(/^[ \t]+|[ \t]+$/, "", $0); print}')
CPU_SPEED=$(lshw -class processor | grep -m 1 'capacity' | cut -d ':' -f 2 | sed 's/^[ \t]*//')
MAX_CPU_SPEED=$
RAM=$(free -h | awk '/^Mem/{print $2}')
DISKS=$(lsblk -d -o NAME,SIZE,MODEL | grep -v "NAME")
VIDEO=$(lspci | grep -i vga | awk -F '[:()]' '{print $3}')

# Network Information
FQDN=$(hostname -f)
HOST_ADDRESS=$(hostname -I)
GATEWAY=$(ip route | awk '/default via/{print $3}')
DNS_SERVER=$(cat /etc/resolv.conf | awk '/nameserver/{print $2}')

INTERFACE=$(ip -o -4 addr show | awk '!/^[0-9]*: ?lo|link\/ether/ {print $2}' | paste -sd "," -)
IP_ADDRESS=$(ip -o -4 addr show | awk '!/^[0-9]*: ?lo|link\/ether/ {print $4}' | cut -d'/' -f1 | paste -sd "," -)

# System Status
USERS=$(who | awk '{print $1}' | sort | uniq | tr '\n' ',')
DISK_SPACE=$(df -h | awk '!/Filesystem/{print $4,$6}')
PROCESS_COUNT=$(ps aux | wc -l)
LOAD_AVERAGES=$(cat /proc/loadavg | awk '{print $1",",$2",",$3}')
MEMORY_ALLOC=$(free -h | awk '/Mem/{print "Total:",$2,"Used:",$3,"Free:",$4}')
LISTENING_PORTS=$(ss -tuln | awk 'NR>1{print $4}' | awk -F: '{print $NF}' | sort -n | uniq | tr '\n' ',')
UFW_RULES=$(sudo ufw status numbered)




#now using the variables, showing that information fornatted.

cat <<EOF


System Report generated by $USER, $(date)

System Information
_________________
Hostname: $HOSTNAME
OS: $OS
Uptime: $UPTIME

Hardware Information
___________________
CPU: $CPU
RAM: $RAM
DISKS:$DISKS
Video: $VIDEO

Network Information
__________________
FQDN: $FQDN
Host Address: $HOST_ADDRESS
Gateway IP: $GATEWAY
DNS Server: $DNS_SERVER

Interface: $INTERFACE
IP Address: $IP_ADDRESS

System Status
_____________
Users Logged In: $USERS
Disk Space:
$DISK_SPACE
Process Count: $PROCESS_COUNT
Load Averages: $LOAD_AVERAGES
Memory Allocations: $MEMORY_ALLOC
Listening Network Ports: $LISTENING_PORTS
UFW Rules: $UFW_RULES

EOF
